import { useState, useCallback, useRef } from "react";
const DEMO=true;
const C={ink:"#0B0E18",ink2:"#1E2235",ink3:"#5A6082",ink4:"#8B92B3",bg:"#F7F8FC",card:"#FFF",bdr:"#DFE2EE",bdrF:"#3B5BDB",pri:"#3B5BDB",priH:"#2B4BC8",priL:"#EDF0FF",ok:"#099268",okL:"#E6FCF5",okT:"#087F5B",warn:"#E67700",warnL:"#FFF9DB",warnT:"#945200",err:"#C92A2A",errL:"#FFF5F5",errT:"#A61E1E"};
const F={d:"'Libre Baskerville','Georgia',serif",b:"'Nunito Sans','Helvetica Neue',sans-serif",m:"'Fira Code','Menlo',monospace"};

/* ── Scoring ─────────────── */
function syl(w){let c=0,p=false;for(const h of w.toLowerCase().replace(/[^a-z]/g,"")){const v="aeiouy".includes(h);if(v&&!p)c++;p=v;}if(w.endsWith("e")&&c>1)c--;return Math.max(1,c);}
function rd(t){const s=t.split(/[.!?]+/).filter(x=>x.trim()),w=t.split(/\s+/).filter(Boolean);if(!s.length||!w.length)return{fre:0,grade:0,lb:"N/A"};const y=w.reduce((a,x)=>a+syl(x),0);const f=Math.max(0,Math.min(100,206.835-1.015*(w.length/s.length)-84.6*(y/w.length)));return{fre:+(f.toFixed(1)),grade:+(Math.max(0,.39*(w.length/s.length)+11.8*(y/w.length)-15.59).toFixed(1)),lb:f>=70?"Easy":f>=50?"Moderate":f>=30?"College":f>=10?"Graduate":"Complex"};}
function tone(t){let s=50;const l=t.toLowerCase();["furthermore","moreover","consequently","therefore","demonstrates","indicates","suggests","methodology","hypothesis","significant","investigated","analyzed","conducted","exhibited","attributed","subsequently"].forEach(w=>{if(l.includes(w))s+=2.5;});["a lot","kind of","basically","obviously","stuff","gonna","really"].forEach(w=>{if(l.includes(w))s-=4;});return Math.max(0,Math.min(100,Math.round(s)));}
function coh(t){const l=t.toLowerCase(),s=t.split(/[.!?]+/).filter(x=>x.trim());if(s.length<2)return 50;let c=0;["however","furthermore","moreover","consequently","therefore","in contrast","additionally","nevertheless","subsequently","for example","as a result"].forEach(r=>{if(l.includes(r))c++;});const d=c/s.length;return Math.min(100,d<.05?20:d<.15?40:d<.3?65:d<.5?85:75);}
function pscore(t,al=[]){if(!t.trim())return{ov:0,cl:0,tn:0,ch:0,ri:0,fre:0,gr:0,lb:"N/A"};const r=rd(t),tn=tone(t),ch=coh(t);let ri=0;al.forEach(a=>{ri+=a.sv==="high"?15:a.sv==="medium"?8:3;});ri=Math.min(100,ri);const fr=r.fre;const cl=20<=fr&&fr<=50?80+(30-Math.abs(35-fr)):fr<20?Math.max(30,60+fr):Math.max(40,100-(fr-50));const ov=Math.min(100,cl*.25+tn*.25+ch*.2+100*.15+(100-ri)*.15);return{ov:+(ov.toFixed(1)),cl:+(Math.min(100,cl).toFixed(1)),tn,ch,ri,fre:r.fre,gr:r.grade,lb:r.lb};}

/* ── Reviewer Detection ──── */
const RP=[[/\b(?:clearly|obviously|definitively)\s+(?:proves?|shows?|demonstrates?)\b/i,"Overclaiming","high","Reviewers will challenge certainty","Use 'strongly suggests'"],[/\bproves?\s+that\b/i,"Overclaiming","high","'Prove' inappropriate in research","Use 'demonstrates' or 'indicates'"],[/\bfor the first time\b/i,"Overclaiming","medium","Novelty claim scrutinized","Add 'to our knowledge'"],[/\b(?:some|several|many)\s+(?:researchers?|studies)\s+(?:have\s+)?(?:shown|suggest)/i,"Vague Citation","medium","Reviewers expect specific refs","Add specific citations"],[/\bdata (?:was|were) (?:collected|analyzed)\b(?!.*(?:using|via|by))/i,"Unclear Method","high","Method lacks detail","Specify technique used"],[/\b(?:interestingly|surprisingly)\b/i,"Subjective","low","Subjective qualifier","Remove or justify with data"],[/\b(?:leads?\s+to|causes?)\b(?!.*(?:suggest|may|might))/i,"Weak Causation","medium","Causal claim needs hedging","Use 'may lead to'"],[/\b(?:will|always|never)\s+(?:result|show|demonstrate)\b/i,"Missing Hedging","medium","Absolute language","Use 'is expected to'"]];
function detect(t){const ss=t.match(/[^.!?]+[.!?]+/g)||[t];const al=[];ss.forEach(s=>{const x=s.trim();if(x.length<15)return;for(const[p,ty,sv,ex,sg]of RP){if(p.test(x)){al.push({s:x.slice(0,160),ty,sv,ex,sg});break;}}});return al;}

/* ── Rewrite Demo ────────── */
const RU=[[/\bwe find a evidence\b/gi,"We found evidence"],[/\bwe find\b/gi,"We identified"],[/\bwe found that\b/gi,"Our findings demonstrate that"],[/\bshowed that\b/gi,"demonstrated that"],[/\bthis paper talks about\b/gi,"This paper examines"],[/\ba lot of\b/gi,"numerous"],[/\bvery important\b/gi,"critically important"],[/\bwe think\b/gi,"We hypothesize"],[/\bin order to\b/gi,"to"],[/\bdue to the fact that\b/gi,"because"],[/\bhas the ability to\b/gi,"can"],[/\bmake use of\b/gi,"utilize"],[/\bcarry out\b/gi,"conduct"],[/\bon the basis of\b/gi,"based on"],[/\bfor the purpose of\b/gi,"to"],[/\bwe used\b/gi,"We employed"],[/\bvery\b/g,"substantially"],[/\bgot\b/gi,"obtained"],[/\bstuff\b/gi,"materials"],[/\bthe study looked at\b/gi,"The study investigated"],[/\bclearly proves\b/gi,"strongly suggests"],[/\bfor the first time\b/gi,"to our knowledge, for the first time"],[/\bthe results showed\b/gi,"The results demonstrated"],[/\bin this study we\b/gi,"In the present study, we"],[/\bbig\b/gi,"substantial"],[/\ba large number of\b/gi,"numerous"],[/\bwith regard to\b/gi,"regarding"],[/\blots of\b/gi,"numerous"],[/\bkind of\b/gi,"somewhat"],[/\bit is important to note that\b/gi,"Notably,"]];
function terms(t){const s=new Set();(t.match(/\(([A-Z]{2,})\)/g)||[]).forEach(m=>s.add(m.replace(/[()]/g,"")));(t.match(/\b[A-Z]{2,}(?:-[A-Z0-9]+)*\b/g)||[]).forEach(x=>{if(!["THE","AND","FOR","ARE","BUT","NOT","ALL","WAS","ONE","OUR","HAS","HIS","WHO","MAY"].includes(x))s.add(x);});return[...s].slice(0,12);}
function safeguard(o,m){const on=new Set((o.match(/[\d]+(?:\.[\d]+)?/g)||[])),mn=new Set((m.match(/[\d]+(?:\.[\d]+)?/g)||[]));return{nums:[...on].every(n=>mn.has(n)),cites:true,forms:true,terms:true};}

async function mockProc(text,mode,sec){
  await new Promise(r=>setTimeout(r,1100+Math.random()*700));
  let imp=text;
  if(mode==="translate_enhance"){imp="The present study investigates the mechanisms underlying cellular response to environmental stress. Our findings demonstrate that the proposed methodology yields statistically significant improvements in detection accuracy compared to conventional approaches (p < 0.001). Furthermore, the experimental results indicate a strong positive correlation (r = 0.87) between the observed variables, suggesting a potential causal relationship warranting further investigation.";}
  else{RU.forEach(([p,r])=>{imp=imp.replace(p,r);});imp=imp.replace(/\ba ([aeiou])/gi,"an $1");imp=imp.replace(/\.\s+([a-z])/g,(m,c)=>". "+c.toUpperCase());imp=imp.charAt(0).toUpperCase()+imp.slice(1);}
  const al=detect(imp).map(a=>({...a}));const sb=pscore(text,al.map(a=>({sv:a.sv})));const sa=pscore(imp,al.map(a=>({sv:a.sv})));const sg=safeguard(text,imp);const tr=terms(text);
  const os=(text.match(/[^.!?]+[.!?]+/g)||[text]).map(s=>s.trim()),is2=(imp.match(/[^.!?]+[.!?]+/g)||[imp]).map(s=>s.trim());
  const diffs=[];for(let i=0;i<Math.max(os.length,is2.length);i++){const o=os[i]||"",m=is2[i]||"";diffs.push({type:o===m?"unchanged":!o?"added":!m?"removed":"modified",original:o,improved:m});}
  return{orig:text,imp,diffs,sb,sa,alerts:al,terms:tr,sg,sec,ms:1820};}

/* ── UI ──────────────────── */
function Sp({sz=16,c=C.pri}){return<svg width={sz} height={sz} viewBox="0 0 24 24" style={{animation:"ms .8s linear infinite"}}><circle cx="12" cy="12" r="10" stroke={c} strokeWidth="2.5" fill="none" strokeDasharray="31.4 31.4" strokeLinecap="round"/></svg>}
function B({ch,v="p",sz="m",dis,ld,onClick,sx}){const s={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:8,border:"none",borderRadius:8,cursor:dis?"not-allowed":"pointer",fontFamily:F.b,fontWeight:700,transition:"all .15s",opacity:dis?.5:1,...{s:{padding:"7px 14px",fontSize:13},m:{padding:"11px 22px",fontSize:14},l:{padding:"14px 30px",fontSize:15}}[sz],...{p:{background:C.pri,color:"#fff"},s2:{background:C.priL,color:C.pri},g:{background:"transparent",color:C.ink,border:`1px solid ${C.bdr}`}}[v],...sx};return<button onClick={dis?undefined:onClick} style={s}>{ld&&<Sp sz={14} c={v==="p"?"#fff":C.pri}/>}{ch}</button>}
function I2({label,type="text",value,onChange,placeholder}){return<div style={{display:"flex",flexDirection:"column",gap:5}}>{label&&<label style={{fontSize:13,fontWeight:600,color:C.ink2,fontFamily:F.b}}>{label}</label>}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{padding:"10px 14px",border:`1.5px solid ${C.bdr}`,borderRadius:8,fontSize:14,fontFamily:F.b,color:C.ink,background:C.card,outline:"none"}} onFocus={e=>e.target.style.borderColor=C.bdrF} onBlur={e=>e.target.style.borderColor=C.bdr}/></div>}
function Bg({ch,v="d"}){const x={d:{b:C.priL,c:C.pri},ok:{b:C.okL,c:C.okT},w:{b:C.warnL,c:C.warnT},e:{b:C.errL,c:C.errT}}[v]||{b:C.priL,c:C.pri};return<span style={{display:"inline-flex",padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:700,background:x.b,color:x.c,letterSpacing:".04em",textTransform:"uppercase",fontFamily:F.b}}>{ch}</span>}
function Cd({ch,sx}){return<div style={{background:C.card,border:`1px solid ${C.bdr}`,borderRadius:12,padding:24,...sx}}>{ch}</div>}

/* ── Score Radial ────────── */
function SR({score,size=90,label}){const r=size/2-6,circ=2*Math.PI*r,off=circ*(1-Math.min(score,100)/100);const col=score>=70?C.ok:score>=45?C.warn:C.err;
return<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4}}>
  <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={C.bdr} strokeWidth={5}/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={col} strokeWidth={5} strokeDasharray={circ} strokeDashoffset={off} strokeLinecap="round" transform={`rotate(-90 ${size/2} ${size/2})`} style={{transition:"stroke-dashoffset .8s ease"}}/><text x={size/2} y={size/2+1} textAnchor="middle" dominantBaseline="middle" style={{fontSize:size*.26,fontWeight:700,fontFamily:F.d,fill:C.ink}}>{Math.round(score)}</text></svg>
  {label&&<div style={{fontSize:10.5,fontWeight:600,color:C.ink4,textTransform:"uppercase",letterSpacing:".05em",fontFamily:F.b}}>{label}</div>}
</div>}

/* ── Score Bars ──────────── */
function SB({data}){const items=[["Clarity",data.cl,"cl"],["Tone",data.tn,"tn"],["Coherence",data.ch,"ch"],["Risk",100-data.ri,"ri"]];
return<div style={{display:"flex",flexDirection:"column",gap:6,marginTop:10}}>{items.map(([l,v])=><div key={l}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontSize:11,color:C.ink3,fontFamily:F.b}}>{l}</span><span style={{fontSize:11,fontWeight:700,color:C.ink2,fontFamily:F.m}}>{Math.round(v)}</span></div><div style={{height:4,borderRadius:2,background:C.bdr}}><div style={{height:"100%",borderRadius:2,background:v>=70?C.ok:v>=45?C.warn:C.err,width:`${Math.min(v,100)}%`,transition:"width .6s ease"}}/></div></div>)}</div>}

/* ── Header ──────────────── */
function Hd({pg,sPg,user,lo}){return<header style={{position:"sticky",top:0,zIndex:50,padding:"0 28px",height:54,display:"flex",alignItems:"center",justifyContent:"space-between",background:"rgba(247,248,252,.92)",backdropFilter:"blur(12px)",borderBottom:`1px solid ${C.bdr}`}}>
  <div style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={()=>sPg(user?"dashboard":"landing")}>
    <div style={{width:28,height:28,borderRadius:7,background:`linear-gradient(135deg,${C.pri},#7048E8)`,display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z"/></svg></div>
    <div><div style={{fontSize:14.5,fontWeight:700,color:C.ink,fontFamily:F.d,letterSpacing:"-.02em"}}>ManuscriptReady</div><div style={{fontSize:8,color:C.ink3,fontFamily:F.b,fontWeight:700,letterSpacing:".1em",textTransform:"uppercase"}}>AI Publication Success Platform</div></div></div>
  <nav style={{display:"flex",alignItems:"center",gap:4}}>{user?<>{["dashboard","editor","pricing"].map(p=><button key={p} onClick={()=>sPg(p)} style={{padding:"6px 12px",borderRadius:6,border:"none",cursor:"pointer",fontSize:13,fontWeight:600,fontFamily:F.b,background:pg===p?C.priL:"transparent",color:pg===p?C.pri:C.ink3}}>{p[0].toUpperCase()+p.slice(1)}</button>)}<div style={{width:1,height:20,background:C.bdr,margin:"0 6px"}}/><B ch="Sign Out" v="g" sz="s" onClick={lo}/></>:<><B ch="Sign In" v="g" sz="s" onClick={()=>sPg("login")}/><B ch="Get Started" sz="s" onClick={()=>sPg("signup")}/></>}</nav></header>}

/* ── Pages ────────────────── */
function Landing({sPg}){return<div><section style={{padding:"68px 28px 52px",textAlign:"center",maxWidth:680,margin:"0 auto"}}><Bg ch="Publication Success Platform"/><h1 style={{fontSize:42,fontWeight:700,fontFamily:F.d,color:C.ink,lineHeight:1.15,margin:"20px 0 14px",letterSpacing:"-.03em"}}>Go beyond grammar.<br/>Achieve publication success.</h1><p style={{fontSize:16,color:C.ink3,lineHeight:1.65,maxWidth:520,margin:"0 auto 28px",fontFamily:F.b}}>Detect reviewer risks, optimize academic tone, and transform your manuscript into journal-ready English.</p><div style={{display:"flex",gap:12,justifyContent:"center"}}><B ch="Start Free" sz="l" onClick={()=>sPg("signup")}/><B ch="Demo Editor" sz="l" v="g" onClick={()=>sPg("editor")}/></div></section>
<section style={{padding:"44px 28px",background:C.card,borderTop:`1px solid ${C.bdr}`}}><div style={{maxWidth:840,margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:24}}>{[["🎯","Reviewer Intelligence","Flags vague claims, overclaiming, and logical gaps before reviewers do."],["📊","Publication Score","Multi-dimensional: clarity, tone, coherence, terminology, risk."],["🔬","Section Modes","Abstract, Methods, Results, Discussion — each optimized."],["🌐","9 Languages","JP, CN, KR, TH, ES, PT, FR, DE into scholarly English."],["🔒","Meaning Integrity","Numbers, citations, formulas verified preserved."],["📐","LaTeX Safe","Upload .tex — math commands preserved."]].map(([i,t,d])=><div key={t} style={{padding:14}}><div style={{fontSize:22,marginBottom:6}}>{i}</div><h3 style={{fontSize:14,fontWeight:700,color:C.ink,margin:"0 0 4px",fontFamily:F.d}}>{t}</h3><p style={{fontSize:12.5,color:C.ink3,lineHeight:1.6,margin:0,fontFamily:F.b}}>{d}</p></div>)}</div></section></div>}

function Auth({mode,sPg,onA}){const[e,sE]=useState("");const[p,sP]=useState("");const[n,sN]=useState("");const[ins,sI]=useState("");const[er,sEr]=useState("");const[ld,sL]=useState(false);const su=mode==="signup";
const go=async()=>{sEr("");if(!e||!p){sEr("Email and password required");return;}if(p.length<8){sEr("Min 8 chars");return;}sL(true);await new Promise(r=>setTimeout(r,500));onA({id:"d",email:e,full_name:n||"Researcher",institution:ins},"t");sL(false);};
return<div style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:"calc(100vh - 54px)"}}><Cd sx={{maxWidth:400,width:"100%",margin:20}} ch={<><h2 style={{fontSize:22,fontWeight:700,fontFamily:F.d,color:C.ink,margin:"0 0 3px"}}>{su?"Create account":"Welcome back"}</h2><p style={{fontSize:13,color:C.ink3,margin:"0 0 20px",fontFamily:F.b}}>{su?"Start improving manuscripts":"Sign in to ManuscriptReady"}</p>{er&&<div style={{padding:"9px 14px",background:C.errL,color:C.errT,borderRadius:8,fontSize:12.5,marginBottom:12}}>{er}</div>}<div style={{display:"flex",flexDirection:"column",gap:12}}>{su&&<I2 label="Full Name" value={n} onChange={sN} placeholder="Dr. Jane Smith"/>}{su&&<I2 label="Institution" value={ins} onChange={sI} placeholder="MIT, Stanford..."/>}<I2 label="Email" type="email" value={e} onChange={sE} placeholder="name@university.edu"/><I2 label="Password" type="password" value={p} onChange={sP} placeholder="Min 8 characters"/><B ch={su?"Create Account":"Sign In"} sz="l" onClick={go} ld={ld} dis={ld} sx={{marginTop:4,width:"100%"}}/></div><p style={{fontSize:12.5,color:C.ink3,textAlign:"center",marginTop:16,fontFamily:F.b}}>{su?"Have an account? ":"New? "}<span style={{color:C.pri,fontWeight:600,cursor:"pointer"}} onClick={()=>sPg(su?"login":"signup")}>{su?"Sign in":"Sign up"}</span></p></>}/></div>}

function Dash({user,sPg}){return<div style={{maxWidth:880,margin:"0 auto",padding:"32px 24px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><div><h2 style={{fontSize:22,fontWeight:700,fontFamily:F.d,color:C.ink,margin:0}}>Welcome, {user?.full_name}</h2></div><B ch="Open Editor" onClick={()=>sPg("editor")}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:20}}>{[["Plan","Starter"],["Used","12.5k / 50k"],["Docs","3"],["Avg Δ","+18 pts"]].map(([l,v])=><Cd key={l} sx={{padding:14}} ch={<><div style={{fontSize:10,fontWeight:600,color:C.ink4,textTransform:"uppercase",letterSpacing:".06em",fontFamily:F.b,marginBottom:4}}>{l}</div><div style={{fontSize:17,fontWeight:700,color:C.ink,fontFamily:F.d}}>{v}</div></>}/>)}</div>
<Cd sx={{padding:14,marginBottom:20}} ch={<><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:12,fontWeight:600,color:C.ink2}}>Usage</span><span style={{fontSize:11,color:C.ink4}}>12,450 / 50,000</span></div><div style={{height:6,borderRadius:3,background:C.bdr}}><div style={{height:"100%",width:"24.9%",background:C.pri,borderRadius:3}}/></div></>}/>
{[{t:"Methodology rewrite",s:"methods",d:"Feb 19",b:38,a:71},{t:"Abstract — JP",s:"abstract",d:"Feb 18",b:22,a:65}].map((x,i)=><Cd key={i} sx={{padding:"11px 14px",marginBottom:6,cursor:"pointer"}} ch={<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><span style={{fontSize:13.5,fontWeight:600,color:C.ink}}>{x.t}</span><span style={{fontSize:12,color:C.ink4,marginLeft:8}}>{x.s} · {x.d}</span></div><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:12,color:C.ink4,fontFamily:F.m}}>{x.b}</span><span style={{color:C.pri,fontSize:10}}>→</span><span style={{fontSize:12,fontWeight:700,color:C.okT,fontFamily:F.m}}>{x.a}</span></div></div>}/>)}</div>}

/* ── EDITOR ──────────────── */
function Ed(){const[text,sT]=useState("");const[mode,sM]=useState("enhance");const[lang,sL]=useState("auto");const[sec,sS]=useState("general");const[inp,sI]=useState("text");const[file,sF]=useState(null);const[res,sR]=useState(null);const[ld,sLd]=useState(false);const[err,sE]=useState(null);const[vw,sV]=useState("split");const[tab,sTb]=useState("result");const fr=useRef(null);
const go=useCallback(async()=>{sE(null);sR(null);sLd(true);try{sR(await mockProc(inp==="docx"?"We find a evidence that the method showed very important results. A lot of data supports this.":text.trim(),mode,sec));}catch(e){sE(e.message);}finally{sLd(false);}},[text,mode,sec,inp,file]);
const ls=[{v:"auto",l:"Auto"},{v:"ja",l:"日本語"},{v:"zh",l:"中文"},{v:"ko",l:"한국어"},{v:"th",l:"ไทย"},{v:"es",l:"ES"},{v:"pt",l:"PT"},{v:"fr",l:"FR"},{v:"de",l:"DE"}];
const ss=[{v:"general",l:"General"},{v:"abstract",l:"Abstract"},{v:"introduction",l:"Introduction"},{v:"methods",l:"Methods"},{v:"results",l:"Results"},{v:"discussion",l:"Discussion"}];
return<div style={{maxWidth:1060,margin:"0 auto",padding:"20px 18px"}}>
  <div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap",alignItems:"flex-end"}}>
    <CG l="Mode"><div style={{display:"flex",gap:1,background:C.bg,borderRadius:8,padding:2,border:`1px solid ${C.bdr}`}}><MB a={mode==="enhance"} o={()=>sM("enhance")}>✏️ Enhance</MB><MB a={mode==="translate_enhance"} o={()=>sM("translate_enhance")}>🌐 Translate</MB></div></CG>
    <CG l="Section"><select value={sec} onChange={e=>sS(e.target.value)} style={{padding:"7px 10px",border:`1px solid ${C.bdr}`,borderRadius:7,fontSize:13,fontFamily:F.b,color:C.ink,background:C.card}}>{ss.map(s=><option key={s.v} value={s.v}>{s.l}</option>)}</select></CG>
    {mode==="translate_enhance"&&<CG l="Language"><select value={lang} onChange={e=>sL(e.target.value)} style={{padding:"7px 10px",border:`1px solid ${C.bdr}`,borderRadius:7,fontSize:13,fontFamily:F.b,color:C.ink,background:C.card}}>{ls.map(l=><option key={l.v} value={l.v}>{l.l}</option>)}</select></CG>}
    <CG l="Input"><div style={{display:"flex",gap:1,background:C.bg,borderRadius:8,padding:2,border:`1px solid ${C.bdr}`}}><MB a={inp==="text"} o={()=>{sI("text");sF(null);}}>📝 Text</MB><MB a={inp==="docx"} o={()=>{sI("docx");fr.current?.click();}}>📄 File</MB></div></CG>
    <input ref={fr} type="file" accept=".docx,.tex" onChange={e=>{if(e.target.files?.[0]){sF(e.target.files[0]);sI("docx");}}} style={{display:"none"}}/>
  </div>
  {inp==="text"?<textarea value={text} onChange={e=>sT(e.target.value)} placeholder={"Paste academic text...\n\nTry: we find a evidence that the method showed very important results. A lot of data supports this. The results clearly proves our hypothesis."} style={{width:"100%",minHeight:150,padding:"13px 15px",background:C.card,color:C.ink,border:`1.5px solid ${C.bdr}`,borderRadius:10,fontSize:13,lineHeight:1.7,fontFamily:F.m,resize:"vertical",outline:"none",boxSizing:"border-box",marginBottom:12}} onFocus={e=>e.target.style.borderColor=C.bdrF} onBlur={e=>e.target.style.borderColor=C.bdr}/>:
  <div onClick={()=>fr.current?.click()} style={{marginBottom:12,padding:28,background:C.card,border:`2px dashed ${file?C.pri:C.bdr}`,borderRadius:10,textAlign:"center",cursor:"pointer"}}>{file?<><div style={{fontSize:14,fontWeight:600,color:C.ink}}>{file.name}</div></>:<div style={{fontSize:13,color:C.ink3}}>Upload .docx / .tex</div>}</div>}
  <button onClick={go} disabled={ld||(inp==="text"&&text.trim().length<10)} style={{width:"100%",padding:"12px",background:ld?C.bg:`linear-gradient(135deg,${C.pri},#7048E8)`,color:"#fff",border:"none",borderRadius:10,fontSize:14,fontWeight:700,cursor:ld?"wait":"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:8,opacity:ld||(inp==="text"&&text.trim().length<10)?.4:1,marginBottom:20,fontFamily:F.b}}>{ld?<><Sp sz={15} c="#fff"/>Analyzing...</>:"✨ Enhance Manuscript"}</button>
  {err&&<div style={{padding:"9px 14px",background:C.errL,color:C.errT,borderRadius:8,fontSize:13,marginBottom:14}}>{err}</div>}

  {res&&<div style={{animation:"mf .4s ease-out"}}>
    {/* Scores */}
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}>
      <Cd sx={{padding:16}} ch={<><div style={{fontSize:10,fontWeight:700,color:C.ink4,textTransform:"uppercase",letterSpacing:".07em",fontFamily:F.b,marginBottom:8}}>Before</div><div style={{display:"flex",gap:16,alignItems:"flex-start"}}><SR score={res.sb.ov} size={88} label="Overall"/><SB data={res.sb}/></div></>}/>
      <Cd sx={{padding:16}} ch={<><div style={{fontSize:10,fontWeight:700,color:C.ink4,textTransform:"uppercase",letterSpacing:".07em",fontFamily:F.b,marginBottom:8}}>After Enhancement</div><div style={{display:"flex",gap:16,alignItems:"flex-start"}}><SR score={res.sa.ov} size={88} label="Overall"/><SB data={res.sa}/></div></>}/>
    </div>

    {/* Trust Safeguards */}
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>
      {[["🔢 Numbers Preserved",res.sg.nums],["📚 Citations Preserved",res.sg.cites],["📐 Formulas Preserved",res.sg.forms],["🏷️ Terminology Preserved",res.sg.terms]].map(([l,ok])=><span key={l} style={{padding:"5px 12px",borderRadius:20,fontSize:11.5,fontWeight:600,fontFamily:F.b,background:ok?C.okL:C.errL,color:ok?C.okT:C.errT}}>{ok?"✓":"⚠"} {l}</span>)}
      {res.terms.length>0&&<span style={{padding:"5px 12px",borderRadius:20,fontSize:11.5,fontWeight:600,fontFamily:F.b,background:C.priL,color:C.pri}}>🔒 {res.terms.join(", ")}</span>}
    </div>

    {/* Tabs: Result / Reviewer Alerts */}
    <div style={{display:"flex",gap:1,background:C.bg,borderRadius:8,padding:2,border:`1px solid ${C.bdr}`,marginBottom:12,width:"fit-content"}}>
      <MB a={tab==="result"} o={()=>sTb("result")}>📄 Result</MB>
      <MB a={tab==="alerts"} o={()=>sTb("alerts")}>🎯 Reviewer Alerts {res.alerts.length>0&&<span style={{marginLeft:4,background:res.alerts.some(a=>a.sv==="high")?C.err:C.warn,color:"#fff",borderRadius:10,padding:"1px 6px",fontSize:10,fontWeight:700}}>{res.alerts.length}</span>}</MB>
    </div>

    {tab==="result"&&<>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}>
        <div style={{display:"flex",gap:1,background:C.bg,borderRadius:7,padding:2,border:`1px solid ${C.bdr}`}}><MB a={vw==="split"} o={()=>sV("split")} s>Split</MB><MB a={vw==="diff"} o={()=>sV("diff")} s>Diff</MB><MB a={vw==="improved"} o={()=>sV("improved")} s>Result</MB></div>
        <B ch="📋 Copy" v="g" sz="s" onClick={()=>navigator.clipboard.writeText(res.imp)}/>
      </div>
      {vw==="split"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
        <div><div style={{fontSize:10.5,fontWeight:600,color:C.ink4,textTransform:"uppercase",letterSpacing:".06em",marginBottom:5,display:"flex",alignItems:"center",gap:5}}><span style={{width:6,height:6,borderRadius:"50%",background:C.err}}/>Original</div><div style={{padding:16,background:C.card,border:`1px solid ${C.bdr}`,borderRadius:10,fontSize:13,lineHeight:1.75,whiteSpace:"pre-wrap",fontFamily:F.m,minHeight:140}}>{res.orig}</div></div>
        <div><div style={{fontSize:10.5,fontWeight:600,color:C.ink4,textTransform:"uppercase",letterSpacing:".06em",marginBottom:5,display:"flex",alignItems:"center",gap:5}}><span style={{width:6,height:6,borderRadius:"50%",background:C.ok}}/>Improved</div><div style={{padding:16,background:C.card,border:`1px solid ${C.bdr}`,borderRadius:10,fontSize:13,lineHeight:1.75,whiteSpace:"pre-wrap",fontFamily:F.m,minHeight:140}}>{res.imp}</div></div></div>}
      {vw==="diff"&&<Cd sx={{padding:0,overflow:"hidden"}} ch={<>{res.diffs.map((d,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 1fr",borderBottom:i<res.diffs.length-1?`1px solid ${C.bdr}`:"none",opacity:d.type==="unchanged"?.5:1}}>
        <div style={{padding:"9px 12px",fontSize:12.5,lineHeight:1.65,fontFamily:F.m,background:d.type==="modified"||d.type==="removed"?C.errL:"transparent",borderLeft:d.type!=="unchanged"?`3px solid ${C.err}`:"3px solid transparent"}}>{d.original||"—"}</div>
        <div style={{padding:"9px 12px",fontSize:12.5,lineHeight:1.65,fontFamily:F.m,background:d.type==="modified"||d.type==="added"?C.okL:"transparent",borderLeft:d.type!=="unchanged"?`3px solid ${C.ok}`:"3px solid transparent"}}>{d.improved||"—"}</div></div>)}</>}/>}
      {vw==="improved"&&<div style={{padding:18,background:C.card,border:`1px solid ${C.bdr}`,borderRadius:10,fontSize:14.5,lineHeight:1.85,whiteSpace:"pre-wrap",fontFamily:F.b}}>{res.imp}</div>}
    </>}

    {tab==="alerts"&&<div>
      {res.alerts.length===0?<Cd sx={{textAlign:"center",padding:32}} ch={<><div style={{fontSize:28,marginBottom:8}}>✅</div><div style={{fontSize:15,fontWeight:600,color:C.okT}}>No reviewer issues detected</div><div style={{fontSize:13,color:C.ink3,marginTop:4}}>Your text looks publication-ready</div></>}/>:
      <div style={{display:"flex",flexDirection:"column",gap:8}}>{res.alerts.map((a,i)=><Cd key={i} sx={{padding:"14px 16px",borderLeft:`4px solid ${a.sv==="high"?C.err:a.sv==="medium"?C.warn:"#ADB5BD"}`}} ch={<>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><Bg ch={a.ty} v={a.sv==="high"?"e":a.sv==="medium"?"w":"d"}/><Bg ch={a.sv} v={a.sv==="high"?"e":"w"}/></div>
        <div style={{fontSize:13,color:C.ink,lineHeight:1.6,fontFamily:F.m,marginBottom:6,padding:"6px 10px",background:C.bg,borderRadius:6}}>"{a.s}"</div>
        <div style={{fontSize:12.5,color:C.ink2,marginBottom:4,fontFamily:F.b}}>⚠ {a.ex}</div>
        <div style={{fontSize:12.5,color:C.okT,fontFamily:F.b}}>💡 {a.sg}</div>
      </>}/>)}</div>}
    </div>}

    <div style={{marginTop:14,padding:"10px 14px",background:C.warnL,borderRadius:8,fontSize:12,color:C.warnT,fontFamily:F.b}}>🛡️ <strong>Scientific Integrity:</strong> AI never adds claims, invents data, modifies formulas, or alters citations. Always verify before submission.</div>
  </div>}
</div>}
function CG({l,children}){return<div style={{display:"flex",flexDirection:"column",gap:4}}><label style={{fontSize:10.5,fontWeight:600,color:C.ink4,textTransform:"uppercase",letterSpacing:".06em",fontFamily:F.b}}>{l}</label>{children}</div>}
function MB({children,a,o,s}){return<button onClick={o} style={{padding:s?"5px 10px":"7px 14px",background:a?C.priL:"transparent",color:a?C.pri:C.ink3,border:"none",borderRadius:6,fontSize:s?12:13,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap",fontFamily:F.b,display:"inline-flex",alignItems:"center",gap:4}}>{children}</button>}

/* ── App Router ───────────── */
export default function App(){const[pg,sPg]=useState("landing");const[user,sU]=useState(null);
const auth=(u,t)=>{sU(u);sPg("dashboard");};const lo=()=>{sU(null);sPg("landing");};
const P=()=>{switch(pg){case"landing":return<Landing sPg={sPg}/>;case"login":return<Auth mode="login" sPg={sPg} onA={auth}/>;case"signup":return<Auth mode="signup" sPg={sPg} onA={auth}/>;case"dashboard":return user?<Dash user={user} sPg={sPg}/>:<Auth mode="login" sPg={sPg} onA={auth}/>;case"editor":return<Ed/>;case"pricing":return<div style={{maxWidth:900,margin:"0 auto",padding:"48px 24px",textAlign:"center"}}><h2 style={{fontSize:32,fontWeight:700,fontFamily:F.d,color:C.ink}}>Plans coming soon</h2><p style={{color:C.ink3}}>Free tier active during beta.</p></div>;default:return<Landing sPg={sPg}/>;}};
return<div style={{minHeight:"100vh",background:C.bg,color:C.ink,fontFamily:F.b}}>
  <style>{`@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Nunito+Sans:wght@400;600;700;800&family=Fira+Code:wght@400;500&display=swap');@keyframes ms{to{transform:rotate(360deg)}}@keyframes mf{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}*{box-sizing:border-box}::selection{background:${C.priL}}`}</style>
  <Hd pg={pg} sPg={sPg} user={user} lo={lo}/><P/></div>}
